import { useEffect, useState } from 'react';

function Footer(params) {

  const { datasets, accessible, isFinal, data } = params;
  
  const [ footnotesShow, setFootnotesShow ] = useState(false);
  const [ technotesShow, setTechnotesShow ] = useState(false);

  useEffect(() => {
    setFootnotesShow(false)
    setTechnotesShow(false)
  }, [isFinal])

  return (
    <div id="footer">
      <button className="header margin" onClick={() => setFootnotesShow(!footnotesShow)} style={{backgroundColor: isFinal ? '#712177' : '#e0e0e0'}}>
        <h2 className="preheader-label" style={{color: isFinal ? 'white' : 'black'}}>Footnotes</h2><span className="toggle-indicator" style={{color: isFinal ? 'white' : 'black'}}>{footnotesShow ? '-' : '+'}</span>
      </button>

      { isFinal && footnotesShow && (
        <>
          <p id="footnote-1"><sup>1</sup>Potential opportunities for intervention included documented evidence of at least one of the following: potential bystander presence, a mental health diagnosis, prior overdose, fatal drug use witnessed, recent release from institutional setting (within 1 month of death), or current treatment for substance use disorder(s). Percentages are only calculated among decedents with an available medical examiner or coroner report. Information represents evidence available in source documents; these are likely underestimated as death investigators might have limited information.</p>
          <p id="footnote-2"><sup>2</sup>In SUDORS, jurisdictions report occurrent drug overdose deaths (i.e., all overdose deaths that occurred within the jurisdiction irrespective of decedent residence). Thus, rates on the SUDORS dashboard are calculated using occurrent deaths for the numerators. From 2020 to 2022, most (~95%)   occurrent deaths included in the SUDORS dashboard occurred in the decedent’s jurisdiction of residency, although this percentage varied for a small number of jurisdictions. Even though SUDORS captures occurrent deaths (both resident and non-resident), occurrent population estimates are generally not available; therefore, rates on the SUDORS dashboard are calculated using resident population estimates for the denominators. In general, resident population estimates appear to be a reasonable proxy for the total population (current resident plus temporary/itinerant) in most jurisdictions. Prior comparisons of rates using occurrent deaths and resident deaths in SUDORS yielded similar results; therefore, the use of resident population-based denominators is recommended as the best/most feasible approach for calculating rates with SUDORS data. The burden of occurrent overdose deaths relative to the jurisdiction population size can be helpful for informing local resource allocation and prevention efforts.</p>
          <p id="footnote-3"><sup>3</sup>“Any opioids” includes deaths that had at least one opioid listed as a cause of death. The “Any opioids” category includes illegally-made fentanyls, heroin, prescription opioids, and any other opioids involved in overdose deaths.</p>
          <p id="footnote-4"><sup>4</sup>Fentanyl was classified as likely illegally made using toxicology, scene, and witness evidence. In the absence of sufficient evidence to classify fentanyl as illegal or prescription, fentanyl was classified as illegally made because the vast majority of fentanyl overdose deaths involve illegally-made fentanyl. All fentanyl analogs except alfentanil, remifentanil, and sufentanil (which have legitimate human medical use) were included as “Illegally-made fentanyls.” IMFs: illegally-made fentanyls.</p>
          <p id="footnote-5"><sup>5</sup>Drugs coded as “Heroin” were heroin and 6-acetylmorphine, a metabolite of heroin. In addition, morphine was coded as heroin if detected along with 6-acetylmorphine or if scene, toxicology, or witness evidence indicated presence of heroin impurities or other illegal drugs, injection, illegal drug use, or a history of heroin use.</p>
          <p id="footnote-6"><sup>6</sup>Drugs coded as “Prescription opioids” were alfentanil, buprenorphine, butorphanol, codeine, dihydrocodeine, hydrocodone, hydromorphone, levorphanol, loperamide, meperidine, methadone, morphine, nalbuphine, noscapine, oxycodone, oxymorphone, pentazocine, prescription fentanyl, propoxyphene, remifentanil, sufentanil, tapentadol, thebaine, and tramadol. Also included as prescription opioids were brand names and metabolites (e.g., nortramadol) of these drugs and combinations of these drugs and nonopioids (e.g., acetaminophen-oxycodone). Morphine was included as prescription only if scene or witness evidence did not indicate likely heroin use and if 6-acetylmorphine was not also detected. Fentanyl was coded as a prescription opioid based on scene, toxicology, or witness evidence indicating that it was in prescribed form (e.g., a fentanyl patch was found at the scene).</p>
          <p id="footnote-7"><sup>7</sup>“Any stimulants” includes deaths that had at least one stimulant listed as a cause of death. The “Any stimulants” category includes cocaine, methamphetamine, and any other stimulants involved in overdose deaths.</p>
          <p id="footnote-8"><sup>8</sup>“Benzodiazepines” includes both prescription benzodiazepines (e.g., alprazolam) and illegal benzodiazepines (e.g., etizolam).</p>
          <p id="footnote-9"><sup>9</sup>“Non-opioid sedatives” includes deaths with gabapentin, kratom/mitragynine, ketamine, medetomidine, or xylazine listed as a cause of death.</p>
          <p id="footnote-10"><sup>10</sup>Percentages are not mutually exclusive. Deaths involving multiple drugs were included in the percentages for each drug (i.e., heroin, cocaine, methamphetamine) or drug class (i.e., any opioids, illegally-made fentanyls, prescription opioids, any stimulants, benzodiazepines, non-opioid sedatives). For example, a death involving both heroin and cocaine would be included in both the heroin and cocaine percentages.</p>
          <p id="footnote-11"><sup>11</sup>Opioid and stimulant drugs or drug combinations include illegally-made fentanyls, heroin, prescription opioids, other opioids (including non-specific opioids or other synthetic opioids such as U-47700 or isotonitazene), cocaine, methamphetamine, and other stimulants (including amphetamines, cathinones, and central nervous system stimulants). If a category does not specify whether other opioids or other stimulants are or are not involved, then the category includes deaths involving the specified drugs (e.g., heroin, methamphetamine) with and without other opioids or other stimulants. If there are ties in the top combinations, they will be presented alphabetically. If there is a tie for the 5th combination, the combination that comes first alphabetically will be presented. The sum of the top 5 combination percentages may not sum to the total in the text due to rounding.</p>
          <p id="footnote-12"><sup>12</sup>SUDORS captures all drugs detected by postmortem toxicology, even those not ruled by a medical examiner or coroner as causing death. Analyses of drugs detected are restricted to jurisdictions with toxicology reports available for at least 75% of deaths in the specified year. Analyses are further restricted to deaths with an available toxicology report.</p>
          <p id="footnote-13"><sup>13</sup>“Other Illegal Opioids” includes deaths with at least one of the following drugs or drug classes detected on postmortem toxicology: nitazene analogs, u-series opioids (e.g., U-47700), 2F-viminol, 2-methyl AP-237, AP-237, AP-238, brorphine, dipyanone, furanyl UF-17, para-methyl AP-237, piperidylthiambutene, UF-17, viminol, or MT-45.</p>
          <p id="footnote-14"><sup>14</sup>“Nitazene analogs” includes deaths with at least one of the following drugs detected on postmortem toxicology: 4-hydroxynitazene, butonitazene, clonitazene, etodesnitazene, etonitazene, flunitazene, isotonitazene, metodesnitazene, metonitazene, n-desethyl isotonitazene, n-piperidinyl etonitazene, n-pyrrolidino etonitazene, n-pyrrolidino metonitazene, n-pyrrolidino protonitazene, or protonitazene.</p>
          <p id="footnote-15"><sup>15</sup>“Illegal Benzodiazepines” includes deaths with at least one of the following drugs detected on postmortem toxicology or listed as a cause of death: 4’-chloro-deschloroalprazolam, 4’-chlorodiazepam, 8-aminoclonazolam, adinazolam, alpha-hydroxyetizolam, bromazolam, clonazolam, delorazepam, deschloroetizolam, diclazepam, etizolam, flualprazolam, flubromazepam, flubromazolam, fluclotizolam, hydroxybromazolam, metizolam, meclonazepam, nitrazolam, nordiclazepam, pyrazolam, or illegal benzodiazepines – not otherwise specified. Illegal benzodiazepines are not approved for human use in the U.S.</p>
          <p id="footnote-16"><sup>16</sup>”Synthetic Cannabinoids” includes deaths with at least one drug belonging to the synthetic cannabinoid class detected on postmortem toxicology (e.g., 5F-MDMB-PICA, 4F-MDMB-BINACA, etc.). Synthetic cannabinoids are lab-made psychoactive substances that are similar in chemical structure to those derived from the cannabis plant but typically cause very different effects. The class includes both illegally-made synthetic cannabinoids as well as those not currently scheduled by the U.S. Food and Drug Administration.</p>
          <p id="footnote-17"><sup>17</sup>Demographic data are restricted to decedents with known information. Thus, the sum of the counts of each category may not add to the total due to missing data.</p>
          <p id="footnote-18"><sup>18</sup>Circumstances represent evidence available in source documents; these are likely underestimated as death investigators might have limited information. Circumstance percentages are only among decedents with an available medical examiner or coroner report and with non-missing information on the specified circumstance.</p>
          <p id="footnote-19"><sup>19</sup>Current treatment for substance use disorders (SUD) included medications for opioid use disorder (MOUD), living in an inpatient rehabilitation facility, or participation in mental health or SUD outpatient treatment.</p>
          <p id="footnote-20"><sup>20</sup>A potential bystander is defined as a person aged ≥11 years who was physically nearby either during or shortly preceding a drug overdose and potentially had an opportunity to intervene or respond to the overdose. This includes any persons in the same structure (e.g., same room or same building, but different room) as the decedent during that time. For example, the family member of an overdose decedent who was in another room during the fatal incident would be considered a potential bystander if that person might have had an opportunity to provide life-saving measures such as naloxone administration, if adequate resources were available and the family member was aware that an overdose event could occur. This does not include, however, persons in different self-contained parts of larger buildings (e.g., a person in a different apartment in the same apartment building would not be considered a potential bystander).</p>
          <p id="footnote-21"><sup>21</sup>Released within a month before death from an institutional setting such as a prison/jail, residential treatment facility, or psychiatric hospital.</p>
          <p id="footnote-22"><sup>22</sup>Includes history of prescription opioid misuse or use of heroin or illegally-made fentanyls.</p>
          <p id="footnote-23"><sup>23</sup>Includes history of cocaine or methamphetamine use.</p>
          <p id="footnote-24"><sup>24</sup>Recent period of opioid use abstinence followed by return to use (within 3 months of the fatal overdose).</p>
          <p id="footnote-25"><sup>25</sup>Persons experiencing homelessness were those who resided in either places not designed for or ordinarily used as regular sleeping accommodations or in a supervised shelter or drop-in center designated to provide temporary living arrangements, congregate shelters, or temporary accommodations provided by a homeless shelter. Persons experiencing housing instability were not experiencing homelessness but lacked the resources or support networks to obtain or retain permanent housing, including interrelated challenges such as trouble paying rent, overcrowding, moving frequently, or staying with relatives.</p>
          <p id="footnote-26"><sup>26</sup>Naloxone is a life-saving medication that can reverse an overdose from opioids, including heroin, fentanyl, and prescription opioid medications.</p>
          <p id="footnote-27"><sup>27</sup>Routes of drug use are not mutually exclusive. A death could have evidence of more than one route of drug use.</p>
          <p id="footnote-28"><sup>28</sup>Evidence of prescription drugs includes pills/tablets, prescription bottles, lozenges/lollipops, patches, liquids, vials, or witness report of prescription drug use. Pills/tablets defined as counterfeit (see definition in later footnote) were not counted as evidence of prescription drugs.</p>
          <p id="footnote-29"><sup>29</sup>Evidence of illegal drugs includes powder, tar, crystal, counterfeit pills, illegal drug packaging, or witness report of illegal drug use.</p>
          <p id="footnote-30"><sup>30</sup>Evidence of counterfeit pills includes pills found at the overdose scene that were identified as counterfeit (e.g., by witnesses, law enforcement, medical examiners, or coroners), pills appearing as oxycodone with no oxycodone detected on postmortem toxicology or appearing as alprazolam with no alprazolam detected, unmarked pills, and pills noted to contain or that tested positive for fentanyl.</p>
        </>
      )}
      {/* {datasets.statesIncluded['prelim_states:']} */}
      {
        !isFinal && footnotesShow && (<>
         <>
          <p id="footnote-1"><sup>1</sup>Jurisdictions include: {datasets.statesIncluded['prelim_states:']}. See Important Data Considerations for more information.</p>
          <p id="footnote-2"><sup>2</sup>Percentages are not mutually exclusive. Deaths involving multiple drugs were included in the percentages for each drug (i.e., heroin, cocaine, methamphetamine) or drug class (i.e., any opioids, illegally-made fentanyls, prescription opioids, any stimulants, benzodiazepines, non-opioid sedatives). For example, a death involving both heroin and cocaine would be included in both the heroin and cocaine percentages.</p>
          <p id="footnote-3"><sup>3</sup>“Any opioids” includes deaths that had at least one opioid listed as a cause of death. The "Any opioids" category includes illegally-made fentanyls, heroin, prescription opioids, and any other opioids involved in overdose deaths.</p>
          <p id="footnote-4"><sup>4</sup>Fentanyl was classified as likely illegally made using toxicology, scene, and witness evidence. In the absence of sufficient evidence to classify fentanyl as illegal or prescription, fentanyl was classified as illegally made because the vast majority of fentanyl overdose deaths involve illegally-made fentanyl. All fentanyl analogs except alfentanil, remifentanil, and sufentanil (which have legitimate human medical use) were included as “Illegally-made fentanyls.” IMFs: illegally-made fentanyls.</p>
          <p id="footnote-5"><sup>5</sup>Drugs coded as heroin were heroin and 6-acetylmorphine. In addition, morphine was coded as heroin if detected along with 6-acetylmorphine or if scene, toxicology, or witness evidence indicated presence of heroin impurities or other illicit drugs, injection, illicit drug use, or a history of heroin use.</p>
          <p id="footnote-6"><sup>6</sup>Drugs coded as “Prescription opioids” were alfentanil, buprenorphine, butorphanol, codeine, dihydrocodeine, hydrocodone, hydromorphone, levorphanol, loperamide, meperidine, methadone, morphine, nalbuphine, noscapine, oxycodone, oxymorphone, pentazocine, prescription fentanyl, propoxyphene, remifentanil, sufentanil, tapentadol, thebaine, and tramadol. Also included as prescription opioids were brand names and metabolites (e.g., nortramadol) of these drugs and combinations of these drugs and nonopioids (e.g., acetaminophen-oxycodone). Morphine was included as prescription only if scene or witness evidence did not indicate likely heroin use and if 6-acetylmorphine was not also detected. Fentanyl was coded as a prescription opioid based on scene, toxicology, or witness evidence indicating that it was in prescribed form (e.g., a fentanyl patch was found at the scene).</p>
          <p id="footnote-7"><sup>7</sup>“Any stimulants” includes deaths that had at least one stimulant listed as a cause of death. The "Any stimulants" category includes cocaine, methamphetamine, and any other stimulants involved in overdose deaths.</p>
          <p id="footnote-8"><sup>8</sup>“Benzodiazepines” includes both prescription benzodiazepines (e.g., alprazolam) and illegal benzodiazepines (e.g., etizolam).</p>
          <p id="footnote-9"><sup>9</sup>“Non-opioid sedatives” includes deaths with gabapentin, kratom/mitragynine, ketamine, medetomidine, or xylazine listed as a cause of death.</p>
          <p id="footnote-10"><sup>10</sup>Opioid and stimulant drugs or drug combinations include illegally-made fentanyls, heroin, prescription opioids, other opioids (including non-specific opioids or other synthetic opioids such as U-47700 or isotonitazene), cocaine, methamphetamine, and other stimulants (including amphetamines, cathinones, and central nervous system stimulants). If a category does not specify whether other opioids or other stimulants are or are not involved, then the category includes deaths involving the specified drugs (e.g., heroin, methamphetamine) with and without other opioids or other stimulants. If there are ties in the top combinations, they will be presented alphabetically. If there is a tie for the 5th combination, the combination that comes first alphabetically will be presented. The sum of the top 5 combination percentages may not sum to the total in the text due to rounding.</p>
          <p id="footnote-11"><sup>11</sup>Demographic data are restricted to decedents with known information. Thus, the sum of the counts of each category may not add to the total due to missing data.</p>
          <p id="footnote-12"><sup>12</sup>Circumstances represent evidence available in source documents; these are likely underestimated as death investigators might have limited information. Circumstance percentages are only among decedents with an available medical examiner or coroner report and with non-missing information on the specified circumstance.</p>
          <p id="footnote-13"><sup>13</sup>Current treatment for substance use disorders (SUD) included medications for opioid use disorder (MOUD), living in an inpatient rehabilitation facility, or participation in mental health or SUD outpatient treatment.</p>
          <p id="footnote-14"><sup>14</sup>A potential bystander is defined as a person aged ≥11 years who was physically nearby either during or shortly preceding a drug overdose and potentially had an opportunity to intervene or respond to the overdose. This includes any persons in the same structure (e.g., same room or same building, but different room) as the decedent during that time. For example, the family member of an opioid overdose decedent who was in another room during the fatal incident would be considered a potential bystander if that person might have had an opportunity to provide life-saving measures such as naloxone administration, if adequate resources were available and the family member was aware that an overdose event could occur. This does not include, however, persons in different self-contained parts of larger buildings (e.g., a person in a different apartment in the same apartment building would not be considered a potential bystander).</p>
          <p id="footnote-15"><sup>15</sup>Released within a month before death from an institutional setting such as a prison/jail, residential treatment facility, or psychiatric hospital.</p>
          <p id="footnote-16"><sup>16</sup>Includes history of prescription opioid misuse or use of heroin or illegally-made fentanyls.</p>
          <p id="footnote-17"><sup>17</sup>Includes history of cocaine or methamphetamine use.</p>
          <p id="footnote-18"><sup>18</sup>Recent period of opioid use abstinence followed by return to use (within 3 months of the fatal overdose).</p>
          <p id="footnote-19"><sup>19</sup>Persons experiencing homelessness were those who resided in either places not designed for or ordinarily used as regular sleeping accommodations or in a supervised shelter or drop-in center designated to provide temporary living arrangements, congregate shelters, or temporary accommodations provided by a homeless shelter. Persons experiencing housing instability were not experiencing homelessness but lacked the resources or support networks to obtain or retain permanent housing, including interrelated challenges such as trouble paying rent, overcrowding, moving frequently, or staying with relatives.</p>
          <p id="footnote-20"><sup>20</sup>Naloxone is a life-saving medication that can reverse an overdose from opioids, including heroin, fentanyl, and prescription opioid medications.</p>
          <p id="footnote-21"><sup>21</sup>Routes of drug use are not mutually exclusive. A death could have evidence of more than one route of drug use.</p>
          <p id="footnote-22"><sup>22</sup>Evidence of prescription drugs includes pills/tablets, prescription bottles, lozenges/lollipops, patches, liquids, vials, or witness report of prescription drug use. Pills/tablets defined as counterfeit (see definition in later footnote) were not counted as evidence of prescription drugs.</p>
          <p id="footnote-23"><sup>23</sup>Evidence of illegal drugs includes powder, tar, crystal, counterfeit pills, illegal drug packaging, or witness report of illegal drug use.</p>
          <p id="footnote-24"><sup>24</sup>Evidence of counterfeit pills includes pills found at the overdose scene that were identified as counterfeit (e.g., by witnesses, law enforcement, medical examiners, or coroners), pills appearing as oxycodone with no oxycodone detected on postmortem toxicology or appearing as alprazolam with no alprazolam detected, unmarked pills, and pills noted to contain or that tested positive for fentanyl.</p>
        </>
        </>)
      }

      <button className="header margin" onClick={() => setTechnotesShow(!technotesShow)} style={{backgroundColor: isFinal ? '#712177' : '#e0e0e0'}}>
        <h2 id="important-data-considerations" className="preheader-label" style={{color: isFinal ? 'white' : 'black'}}>Important Data Considerations</h2><span className="toggle-indicator" style={{color: isFinal ? 'white' : 'black'}}>{technotesShow ? '-' : '+'}</span>
      </button>
      
      { isFinal && technotesShow && (
        <>
          <p>Data come from death certificate information, medical examiner or coroner reports, and forensic toxicology results entered into the State Unintentional Drug Overdose Reporting System (SUDORS). Jurisdictions report occurrent drug overdose deaths (i.e., all overdose deaths that occurred within the jurisdiction regardless of decedent residence). Percentages are among decedents with known information (e.g., counts for demographic data and month of death may not add to the total due to missing information). Drug-, sex-, and race/ethnicity-specific rates are age-standardized to the 2010 U.S. Census population. The number of deaths, and corresponding rates, in SUDORS might not match the number and rate in <a target="_blank" href="https://wonder.cdc.gov/">CDC’s Wide-ranging Online Data for Epidemiologic Research (CDC WONDER)<span className="fi cdc-icon-external icon icon-fw x16" aria-hidden="true"></span></a>.</p> 
          <p>The <a target="_blank" href="https://cdn.ymaws.com/www.safestates.org/resource/resmgr/imported/ISW7%20Full%20Report_3.pdf">Injury Surveillance Workgroup 7 consensus definition of a drug<span className="fi cdc-icon-external icon icon-fw x16" aria-hidden="true"></span></a> is used to determine whether a death meets the SUDORS case definition. A drug is any chemical compound that is chiefly used by or administered to humans or animals as an aid in the diagnosis, treatment, or prevention of disease or injury, for the relief of pain or suffering, to control or improve any physiologic or pathologic condition, or for the feeling it causes. This definition specifically includes: illegal drugs such as heroin and cocaine; prescription drugs; over-the-counter drugs; biological substances such as vaccinations; veterinary drugs; dietary supplements; and non-medicinal substances used primarily for the feeling they cause. This definition specifically excludes: alcohol; tobacco; and chemicals that are deliberately inhaled for the feeling they cause but are chiefly used for other purposes (i.e., organic solvents and halogen derivatives of aliphatic and aromatic hydrocarbons).</p> 
          <p>Jurisdictions that reported all overdose deaths in their jurisdiction for the selected year, and had medical examiner or coroner reports for at least 75% of deaths in that year, are included in this dashboard. The Overall category may not be comparable across years because different jurisdictions may be included in different years based on data availability and completeness. The Overall category includes the jurisdictions listed in the jurisdiction selection drop-down box for the selected year. Data are based on information entered into the SUDORS web-based system by {data && data["dataset_date"]}. Information entered into the web-based system after this date will not be included and therefore may not match more recent jurisdiction data.</p>
          <p>Drugs were classified as involved in overdose deaths if the medical examiner or coroner listed them as causing death on the death certificate, or in the medical examiner or coroner report or postmortem toxicology report.</p>
          <p>Rates are calculated using population estimates from the U.S. Census Bureau. Beginning with the release of the 2021 data, the U.S. Census Bureau instituted new methodology to calculate population estimates. The new methodology, referred to as <a href="https://www.ncsl.org/research/redistricting/differential-privacy-for-census-data-explained.aspx" target="_blank">differential privacy</a>, ensures that data from individuals and individual households remain confidential. Therefore, rates for 2021 and forward may not be directly comparable to 2020 rates.</p>
          <p>Deaths involving multiple drugs were included in the rates for each drug class. In SUDORS, when the cause of death indicated multiple drugs were involved but did not indicate specific drugs, all drugs detected by postmortem toxicology testing were classified as involved in the drug overdose death. For example, if the cause of death was “multidrug overdose” and toxicology results were positive for five drugs, all five were classified as involved.</p>
          <p>Race/ethnicity categories were changed from prior versions of the dashboard to remove non-Hispanic Native Hawaiian and Other Pacific Islander from the non-Hispanic Asian or Pacific Islander category into their own category.</p>
          <p>Rates based on &lt;20 drug overdose deaths are suppressed to avoid presentation of unstable rates{accessible ? '' : ' and denoted by an *'}.</p>
          <p>Additional information about how fields in SUDORS are defined and coded can be found in the <a href='https://www.cdc.gov/drugoverdose/fatal/pdf/SUDORS_Coding_Manual_OD2A_v6.3.pdf' target='_blank'>SUDORS Coding Manual</a>.</p>
        </>
      )}
      {
        !isFinal && technotesShow && (<><p>Data come from death certificate information, medical examiner or coroner reports, and forensic toxicology results entered into the State Unintentional Drug Overdose Reporting System (SUDORS). Jurisdictions report occurrent drug overdose deaths (i.e., all overdose deaths that occurred within the jurisdiction regardless of decedent residence). Percentages are among decedents with known information. The number of deaths in SUDORS might not match the number in CDC WONDER.</p> 
        <p>Preliminary SUDORS data represent a more recent timeframe than final SUDORS data and have not undergone the same quality control measures as finalized data. Preliminary data may change once finalized; thus, preliminary data are not available for download. Preliminary data for a given timeframe should not be used once final data for that timeframe are available; when the preliminary data become finalized, they will be added to the final data page and removed from the preliminary data page.</p>
        <p>Preliminary data are updated approximately every six months (as opposed to annually for the final data). Depending on the update, the preliminary data page may show overdose deaths occurring either during January–June or January–December of the specified year. The preliminary data are presented as an aggregate of all included jurisdictions for the specified timeframe. Preliminary data at the jurisdiction-level are not shown because smaller numbers are subject to greater variability. Jurisdictions that reported all overdose deaths in their jurisdiction for the specified timeframe and had medical examiner/coroner reports for at least 75% of deaths in that timeframe are included in the preliminary version of this dashboard. The included jurisdictions are specified in the footnotes.</p>
        <p>Because the data are preliminary, each percentage has a corresponding 95% confidence interval that is calculated using <a href='https://doi.org/10.1201/9780429246593' target='_blank'>bootstrapping</a>, a random sampling with replacement procedure, with 1,000 bootstraps.</p>
        <p>The <a href='https://cdn.ymaws.com/www.safestates.org/resource/resmgr/imported/ISW7 Full Report_3.pdf' target='_blank'>Injury Surveillance Workgroup 7 consensus definition of a drug</a> is used to determine SUDORS case. A drug is any chemical compound that is chiefly used by or administered to humans or animals as an aid in the diagnosis, treatment, or prevention of disease or injury, for the relief of pain or suffering, to control or improve any physiologic or pathologic condition, or for the feeling it causes. This definition specifically includes: street drugs such as heroin, cocaine, and hallucinogens; prescription drugs; over-the-counter drugs; biological substances such as vaccinations; veterinary drugs; dietary supplements; and non-medicinal substances used primarily for the feeling they cause. This definition specifically excludes: alcohol; tobacco; and chemicals that are deliberately inhaled for the feeling they cause but are chiefly used for other purposes (i.e., organic solvents and halogen derivatives of aliphatic and aromatic hydrocarbons).</p>
        <p>Drugs were classified as involved in overdose deaths if the medical examiner/coroner listed them as causing death on the death certificate, or in the medical examiner/coroner report, or postmortem toxicology report. When the cause of death indicated multiple drugs were involved but did not indicate specific drugs, all drugs detected by postmortem toxicology testing were classified as involved in the drug overdose death. For example, if the cause of death was “multidrug overdose” and toxicology results were positive for five drugs, all five were classified as involved.</p>
        <p>Additional information about how fields in SUDORS are defined and coded can be found in the <a href='https://www.cdc.gov/drugoverdose/fatal/pdf/SUDORS_Coding_Manual_OD2A_v6.3.pdf' target='_blank'>SUDORS Coding Manual</a>.</p>
      </>)
      }
    </div>
  );
}

export default Footer;